# Generated by Django 4.2.5 on 2023-10-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('designation', models.TextField()),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
